---
- name: Install gnupg
  ansible.builtin.package:
    name: gnupg
    state: present

- name: Ensure keyring directory exists.
  ansible.builtin.file:
    name: '/etc/apt/keyrings'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download the PDNS auth APT Repository key
  ansible.builtin.get_url:
    url: "{{ pdns_install_repo['gpg_key_url'] }}"
    dest: "/etc/apt/keyrings/{{ pdns_install_repo['gpg_key_file'] }}"
    owner: root
    group: root
    mode: '0644'
  notify: Update the APT cache

- name: Create the PDNS auth APT repository Deb822 source
  ansible.builtin.template:
    src: 'pdns-auth.sources.j2'
    dest: "/etc/apt/sources.list.d/{{ pdns_install_repo['name'] }}.sources"
    owner: root
    group: root
    mode: '0644'
  notify: Update the APT cache

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Pin the PowerDNS APT Repository
  ansible.builtin.template:
    src: pdns.pin.j2
    dest: /etc/apt/preferences.d/pdns
    owner: root
    group: root
    mode: '0644'
